import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import { X, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface TermsOfServiceProps {
  trigger?: React.ReactNode;
}

export default function TermsOfService({ trigger }: TermsOfServiceProps) {
  const [isOpen, setIsOpen] = useState(false);

  const modalContent = (
    <AnimatePresence>
      {isOpen && (
        <div 
          className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-black/80 backdrop-blur-md overflow-y-auto"
          onClick={() => setIsOpen(false)}
        >
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            className="bg-[#FAF9F5] border border-[var(--border2)] rounded-2xl shadow-2xl w-full max-w-2xl relative my-auto flex flex-col max-h-[90vh]"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-6 border-b border-[var(--border)] flex items-center justify-between shrink-0">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-[var(--blue2)]/10 rounded-lg text-[var(--blue)]">
                  <FileText className="w-5 h-5" />
                </div>
                <h2 className="text-xl font-bold text-[var(--blue2)]">Terms of Service</h2>
              </div>
              <button onClick={() => setIsOpen(false)} className="p-2 hover:bg-black/5 rounded-full transition-colors">
                <X className="w-5 h-5 text-[var(--muted)]" />
              </button>
            </div>

            <div className="p-8 overflow-y-auto text-[var(--muted)] space-y-8 text-sm leading-relaxed">
              <div className="space-y-1">
                <p className="font-bold text-[var(--text)]">Effective Date: April 9, 2026</p>
                <p className="font-bold text-[var(--text)]">Last Updated: April 9, 2026</p>
              </div>

              <p>
                These Terms of Service ("Terms") govern your access to and use of the Veridian web
                application (the "Service") operated by Veridian ("Veridian," "we," "us," or "our").
                By accessing or using the Service, you agree to be bound by these Terms.
              </p>

              <section className="space-y-3">
                <h3 className="text-[var(--text)] font-bold text-base">1. Description of Service</h3>
                <p>
                  Veridian provides an AI-powered tool that compares two proposal or pricing documents and
                  generates structured differences, summaries, and reports.
                  The Service is provided as a <span className="text-[var(--blue)] font-bold">stateless, session-based application</span> with no persistent storage of
                  user data.
                </p>
              </section>

              <section className="space-y-3">
                <h3 className="text-[var(--text)] font-bold text-base">2. Eligibility</h3>
                <p>
                  You must be at least 18 years old and legally capable of entering into binding agreements to use
                  the Service.
                </p>
              </section>

              <section className="space-y-3">
                <h3 className="text-[var(--text)] font-bold text-base">3. User Responsibilities</h3>
                <p>You agree that you will:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li>Upload only files that you have the legal right to use and process</li>
                  <li>Ensure compliance with your organization's data handling policies</li>
                  <li>Not upload unlawful, infringing, or malicious content</li>
                  <li>Not attempt to reverse engineer, disrupt, or misuse the Service</li>
                </ul>
                <p>You are solely responsible for:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li>The content of uploaded files</li>
                  <li>Any decisions made based on outputs generated by the Service</li>
                </ul>
              </section>

              <section className="space-y-3">
                <h3 className="text-[var(--text)] font-bold text-base">4. Data Handling and Privacy</h3>
                <p>Use of the Service is subject to our Privacy Policy.</p>
                <p className="font-bold text-[var(--text)]">Key principles:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li>No file storage or retention</li>
                  <li>No user accounts</li>
                  <li>Session-based processing only</li>
                </ul>
              </section>

              <section className="space-y-3">
                <h3 className="text-[var(--text)] font-bold text-base">5. AI-Generated Outputs Disclaimer</h3>
                <p>Veridian uses automated systems, including AI, to generate outputs. You acknowledge that:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li>Outputs may contain errors, omissions, or inaccuracies</li>
                  <li>Results are <span className="text-[var(--text)] font-bold">not guaranteed to be complete, accurate, or fit for purpose</span></li>
                  <li>You are responsible for reviewing and validating all outputs before use</li>
                </ul>
              </section>

              <section className="space-y-3 pb-4">
                <h3 className="text-[var(--text)] font-bold text-base">6. No Professional Advice</h3>
                <p>The Service does not provide legal, financial, procurement, or professional advice.</p>
              </section>
            </div>

            <div className="p-6 bg-[var(--navy)] border-t border-[var(--border)] flex justify-end shrink-0">
              <button
                onClick={() => setIsOpen(false)}
                className="px-8 py-2.5 bg-[var(--blue2)] text-white rounded-xl font-bold hover:opacity-90 transition-all shadow-md shadow-[var(--blue2)]/10"
              >
                Close
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );

  return (
    <>
      <div onClick={() => setIsOpen(true)} className="cursor-pointer">
        {trigger || <span className="hover:text-[var(--text)] transition-colors">Terms of Service</span>}
      </div>
      {createPortal(modalContent, document.body)}
    </>
  );
}
